# Site settings
title: turretcss
page_title: turretcss - A Responsive Front-end Framework for Accessible and Semantic Websites
email: scottdj@bigfish.tv
description: Developed for design. turretcss is a styles and browser behaviour normalisation framework for rapid development of responsive and accessible websites.

# Permalinks
permalink: pretty

# Server
baseurl: ""
source: ""
destination: _site
host: 0.0.0.0
port: 2001
url: https://turretcss.com
encoding: UTF-8
exclude: []

# Custom vars
current_version: 5.0.0-alpha4
repo: https://github.com/turretcss/turretcss
twitter: https://twitter.com/turretcss
cdn: https://cdnjs.cloudflare.com/ajax/libs/bigfishtv-turret/4.0.0/turret.min.css