# Site settings
title: Turret
page_title: Turret - A Responsive Front-end Framework for Accessible and Semantic Websites
email: scottdj@bigfish.tv
description: Developed for design. Turret is a styles and browser behaviour normalisation framework for rapid development of responsive and accessible websites.

# Permalinks
permalink: pretty

# Syntax Highlighter
highlighter: rouge

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Server
baseurl: ""
source: ""
destination: _site
host: 0.0.0.0
port: 2001
url: http://turretcss.com
encoding: UTF-8
exclude: []

# Custom vars
current_version: 4.0.0
repo: https://github.com/bigfishtv/turret
twitter: https://twitter.com/turretcss
cdn: https://cdnjs.cloudflare.com/ajax/libs/turretcss/4.0.0/turret.min.css